# Generated by Django 2.1.7 on 2019-04-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCrawling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_server', models.CharField(max_length=45)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'time_crawling',
            },
        ),
        migrations.RemoveField(
            model_name='voting',
            name='record_at',
        ),
        migrations.AddField(
            model_name='voting',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votings', to='app.TimeCrawling'),
        ),
    ]
