# Generated by Django 2.1.7 on 2019-04-23 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190422_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecrawling',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterField(
            model_name='timecrawling',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 20, 50, 34, 402372)),
        ),
    ]
