# Generated by Django 2.1.7 on 2019-04-23 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190423_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecrawling',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 21, 13, 51, 2621)),
        ),
    ]
