# Generated by Django 2.1.7 on 2019-04-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190423_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecrawling',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
