# Generated by Django 2.1.7 on 2019-04-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190423_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecrawling',
            options={'ordering': ['-time_server']},
        ),
    ]
