# Generated by Django 2.1.7 on 2019-04-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190425_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecrawling',
            name='total_noldua',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='timecrawling',
            name='total_nolsatu',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
