# Generated by Django 2.1.7 on 2019-04-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190426_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecrawling',
            old_name='total',
            new_name='percentage_tps',
        ),
        migrations.AddField(
            model_name='timecrawling',
            name='process_tps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timecrawling',
            name='total_suara',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timecrawling',
            name='total_tps',
            field=models.FloatField(default=0),
        ),
    ]
